name: Smart Portfolio Automation
'on':
  workflow_dispatch:
    inputs:
      project_id:
        description: Project ID
        required: true
        type: string
    project_source:
      description: Project Source (Node or Local)
      required: true
      type: string
    pipeline_type:
      description: Pipeline type (Analysis)
      required: true
      type: string
    correlation_id:
      description: Correlation ID for tracking
      required: true
      type: string
    project_name:
      description: Project Name
      required: true
      type: string
    project_status:
      desription: Project Status
      required: true
      type: string
  jobs:
    analyze:
      runs-on: ubuntu-latest
      steps:
        - name: Show inputs (debug)
          run: |
            echo "Project ID: ${{ github.event.inputs.project_id }}"
            echo "Project Source: ${{ github.event.inputs.project_source }}"
            echo "Pipeline Type: ${{ github.event.inputs.pipeline_type }}"
            echo "Correlation ID: ${{ github.event.inputs.correlation_id }}"
            echo "Project Name: ${{ github.event.inputs.project_name }}"
            echo "Project Status: ${{ github.event.inputs.project_status }}"  
